import type { NextPage } from "next";
import Head from "next/head";
import AppLayout from "../layouts/app.layout";

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Music App</title>
				<meta name="description" content="Generated by create next app" />
				{/* <link rel="icon" href="/favicon.ico" /> */}
			</Head>

			<AppLayout>
				<div className="py-3">
					<div className="search-input">
						<i className="fas fa-magnifying-glass"></i>
						<input type="text" placeholder="Search artists" />
					</div>
					<p>Hello</p>
				</div>
			</AppLayout>
		</>
	);
};

export default Home;
